In [49]:
import numpy as np
import pandas as pd
import os

Data cleaning process:

In [ ]:
obesity_dataset_raw = pd.read_csv("/Users/vivekkumar/Downloads/dataset.csv")

print(obesity_dataset_raw.head(10))

   hjdjhjdj  Gender  Height   Weight  eating habits (CALC  FAVC   FCVC   NCP  \
0      21.0  Female    1.62     64.0                   no    no    2.0   3.0
1      21.0  Female    1.52     56.0            Sometimes    no    3.0   3.0
2      23.0    Male     1.8     77.0           Frequently    no    2.0   3.0
3      27.0    Male     1.8     87.0           Frequently    no    3.0   3.0
4      22.0    Male    1.78     89.8            Sometimes    no    2.0   1.0
5      29.0    Male    1.62     53.0            Sometimes   yes    2.0   3.0
6      23.0  Female     1.5     55.0            Sometimes   yes    3.0   3.0
7      22.0    Male    1.64     53.0            Sometimes    no    2.0   3.0
8      24.0    Male    1.78     64.0           Frequently   yes    3.0   3.0
9      22.0    Male    1.72     68.0                   no   yes    2.0   3.0

   SCC  SMOKE   CH2O  CAEC)   physical activity level (FAF)  \
0   no     no    2.0    yes                             0.0
1  yes    yes    3.0    yes                             3.0
2   no     no    2.0    yes                             2.0
3   no     no    2.0     no                             2.0
4   no     no    2.0     no                             0.0
5   no     no    2.0     no                             0.0
6   no     no    2.0    yes                             1.0
7   no     no    2.0     no                             3.0
8   no     no    2.0    yes                             1.0
9   no     no    2.0    yes                             1.0

    usage time of technology devices (TUE)  modes of transportation (MTRANS)  \
0                                      1.0                         Sometimes
1                                      0.0                         Sometimes
2                                      1.0                         Sometimes
3                                      0.0                         Sometimes
4                                      0.0                         Sometimes
5                                      0.0                         Sometimes
6                                      0.0                         Sometimes
7                                      0.0                         Sometimes
8                                      1.0                         Sometimes
9                                      1.0                         Sometimes

   and the family history of being overweight. The dataset doesnt only account for quantitative metrics but also integrates qualitative assessments  \
0                              Public_Transportation
1                              Public_Transportation
2                              Public_Transportation
3                                            Walking
4                              Public_Transportation
5                                         Automobile
6                                          Motorbike
7                              Public_Transportation
8                              Public_Transportation
9                              Public_Transportation

   providing a holistic view of factors contributing to obesity. With entries from various age groups and both genders  \
0                                      Normal_Weight
1                                      Normal_Weight
2                                      Normal_Weight
3                                 Overweight_Level_I
4                                Overweight_Level_II
5                                      Normal_Weight
6                                      Normal_Weight
7                                      Normal_Weight
8                                      Normal_Weight
9                                      Normal_Weight

    thisdatasencapsulatesadetailedrepresentationoflifestylechoicesandtheirpotentialimpactonweightcategories  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

    classifiedundertheattributeNobeyesdad
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
5                                     NaN
6                                     NaN
7                                     NaN
8                                     NaN
9                                     NaN

Seeing all the column name and cleaning them. Rename them more understandable in first glance.

In [110]:
print(obesity_dataset_raw.columns)

Index(['hjdjhjdj', ' Gender', ' Height', ' Weight', ' eating habits (CALC',
       ' FAVC', ' FCVC', ' NCP', ' SCC', ' SMOKE', ' CH2O', ' CAEC)',
       ' physical activity level (FAF)',
       ' usage time of technology devices (TUE)',
       ' modes of transportation (MTRANS)',
       ' and the family history of being overweight. The dataset doesnt only account for quantitative metrics but also integrates qualitative assessments',
       ' providing a holistic view of factors contributing to obesity. With entries from various age groups and both genders',
       ' thisdatasencapsulatesadetailedrepresentationoflifestylechoicesandtheirpotentialimpactonweightcategories',
       ' classifiedundertheattributeNobeyesdad'],
      dtype='object')

The whole dataset has columns with abbrevation. Which are hard to understand. So we need undergo the data cleaning process. In data cleaning, We look that data has a missing, duplicate values or incorrect data. In the step below we try to simplify the names of columns. The dataset contains two columns with no values we have drop those columns.

In [111]:
obesity_dataset_raw.rename(columns={
    'hjdjhjdj': 'Age',
    ' eating habits (CALC': 'Alcohol_consumption',
    ' FAVC': 'High_calories_foodconsumption_frequency',
    ' FCVC': 'Vegetable_consumption_frequency',
    ' NCP': 'Avg_no_of_meals',
    ' SCC': 'Calorie_consumption_monitoring',
    ' SMOKE': 'Smoking_habits',
    ' CH2O': 'Water_consumption',
    ' CAEC)': 'Family_history',
    ' physical activity level (FAF)': 'Physical_activity',
    ' usage time of technology devices (TUE)': 'Mobile_screentime',
    ' modes of transportation (MTRANS)': 'Food_consumed_between_meals',
    ' and the family history of being overweight. The dataset doesnt only account for quantitative metrics but also integrates qualitative assessments': 'Transpotation',
    ' providing a holistic view of factors contributing to obesity. With entries from various age groups and both genders': 'obesity_level'
}, inplace=True)

Downloaded the test csv file

In [114]:
obesity_dataset_raw.to_csv('obesity_test.csv', index=False)

In [115]:
print(obesity_dataset_raw.columns)

Index(['Age', ' Gender', ' Height', ' Weight', 'Alcohol_consumption',
       'High_calories_foodconsumption_frequency',
       'Vegetable_consumption_frequency', 'Avg_no_of_meals',
       'Calorie_consumption_monitoring', 'Smoking_habits', 'Water_consumption',
       'Family_history', 'Physical_activity', 'Mobile_screentime',
       'Food_consumed_between_meals', 'Transpotation', 'obesity_level',
       ' thisdatasencapsulatesadetailedrepresentationoflifestylechoicesandtheirpotentialimpactonweightcategories',
       ' classifiedundertheattributeNobeyesdad'],
      dtype='object')

Dropped the columns. The columns have no information

In [116]:
obesity_dataset_begin = obesity_dataset_raw.drop([' thisdatasencapsulatesadetailedrepresentationoflifestylechoicesandtheirpotentialimpactonweightcategories'], axis=1)

In [117]:
obesity_dataset_begin = obesity_dataset_begin.drop([' classifiedundertheattributeNobeyesdad'], axis=1)

In [118]:
print(obesity_dataset_begin.columns)

Index(['Age', ' Gender', ' Height', ' Weight', 'Alcohol_consumption',
       'High_calories_foodconsumption_frequency',
       'Vegetable_consumption_frequency', 'Avg_no_of_meals',
       'Calorie_consumption_monitoring', 'Smoking_habits', 'Water_consumption',
       'Family_history', 'Physical_activity', 'Mobile_screentime',
       'Food_consumed_between_meals', 'Transpotation', 'obesity_level'],
      dtype='object')

Downloading cleaning csv file.

In [119]:
obesity_dataset_begin.to_csv('obesity_cleaned.csv', index=False)

Looking for missing values or null values.

In [120]:
print(obesity_dataset_begin.isnull().sum())

Age                                        0
 Gender                                    0
 Height                                    0
 Weight                                    0
Alcohol_consumption                        0
High_calories_foodconsumption_frequency    0
Vegetable_consumption_frequency            0
Avg_no_of_meals                            0
Calorie_consumption_monitoring             0
Smoking_habits                             0
Water_consumption                          0
Family_history                             0
Physical_activity                          0
Mobile_screentime                          0
Food_consumed_between_meals                0
Transpotation                              0
obesity_level                              0
dtype: int64

The above line indicated no missing values.

In [123]:
obesity_dataset_begin.head(10)

,Age,Gender,Height,Weight,Alcohol_consumption,High_calories_foodconsumption_frequency,Vegetable_consumption_frequency,Avg_no_of_meals,Calorie_consumption_monitoring,Smoking_habits,Water_consumption,Family_history,Physical_activity,Mobile_screentime,Food_consumed_between_meals,Transpotation,obesity_level
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.8,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.8,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,29.0,Male,1.62,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,23.0,Female,1.5,55.0,Sometimes,yes,3.0,3.0,no,no,2.0,yes,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,22.0,Male,1.64,53.0,Sometimes,no,2.0,3.0,no,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,24.0,Male,1.78,64.0,Frequently,yes,3.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
9,22.0,Male,1.72,68.0,no,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In the cleaning process, we noticed that the age column has decimal values. Which cannot be happended. so we converted them into integer values.

In [124]:
obesity_dataset_begin['Age'] = obesity_dataset_begin['Age'].astype(int)

In [125]:
obesity_dataset_begin.head(10)

,Age,Gender,Height,Weight,Alcohol_consumption,High_calories_foodconsumption_frequency,Vegetable_consumption_frequency,Avg_no_of_meals,Calorie_consumption_monitoring,Smoking_habits,Water_consumption,Family_history,Physical_activity,Mobile_screentime,Food_consumed_between_meals,Transpotation,obesity_level
0,21,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23,Male,1.8,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27,Male,1.8,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,29,Male,1.62,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,23,Female,1.5,55.0,Sometimes,yes,3.0,3.0,no,no,2.0,yes,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,22,Male,1.64,53.0,Sometimes,no,2.0,3.0,no,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,24,Male,1.78,64.0,Frequently,yes,3.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
9,22,Male,1.72,68.0,no,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

The data set has two columns height and weight, which can be drop by getting bmi as value

In [127]:
obesity_dataset_begin['Weight'] = pd.to_numeric(obesity_dataset_begin[' Weight'], errors='coerce')
obesity_dataset_begin['Height'] = pd.to_numeric(obesity_dataset_begin[' Height'], errors='coerce')

obesity_dataset_begin['Bmi_index'] = obesity_dataset_begin['Weight'] / (obesity_dataset_begin['Height'] ** 2)
obesity_dataset_begin.drop([' Weight', ' Height'], axis=1, inplace=True)

In [128]:
obesity_dataset_begin = obesity_dataset_begin.drop(['Weight'], axis=1)
obesity_dataset_begin = obesity_dataset_begin.drop(['Height'], axis=1)

In [129]:
obesity_dataset_begin.head(10)

,Age,Gender,Alcohol_consumption,High_calories_foodconsumption_frequency,Vegetable_consumption_frequency,Avg_no_of_meals,Calorie_consumption_monitoring,Smoking_habits,Water_consumption,Family_history,Physical_activity,Mobile_screentime,Food_consumed_between_meals,Transpotation,obesity_level,Bmi_index
0,21,Female,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight,24.386526
1,21,Female,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,24.238227
2,23,Male,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,23.765432
3,27,Male,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I,26.851852
4,22,Male,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,28.342381
5,29,Male,Sometimes,yes,2.0,3.0,no,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,20.195092
6,23,Female,Sometimes,yes,3.0,3.0,no,no,2.0,yes,1.0,0.0,Sometimes,Motorbike,Normal_Weight,24.444444
7,22,Male,Sometimes,no,2.0,3.0,no,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,19.705532
8,24,Male,Frequently,yes,3.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,20.199470
9,22,Male,no,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,22.985398

In [130]:
obesity_dataset_begin.isnull().sum()

Age                                        0
 Gender                                    0
Alcohol_consumption                        0
High_calories_foodconsumption_frequency    0
Vegetable_consumption_frequency            0
Avg_no_of_meals                            0
Calorie_consumption_monitoring             0
Smoking_habits                             0
Water_consumption                          0
Family_history                             0
Physical_activity                          0
Mobile_screentime                          0
Food_consumed_between_meals                0
Transpotation                              0
obesity_level                              0
Bmi_index                                  1
dtype: int64

In [131]:
obesity_dataset_begin['Bmi_index'].fillna(obesity_dataset_begin['Bmi_index'].mean(), inplace=True)

/var/folders/8q/k_54hxvx05x5ml7_73sk06wm0000gn/T/ipykernel_36540/68817635.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  obesity_dataset_begin['Bmi_index'].fillna(obesity_dataset_begin['Bmi_index'].mean(), inplace=True)

In [132]:
obesity_dataset_begin.isnull().sum()

Age                                        0
 Gender                                    0
Alcohol_consumption                        0
High_calories_foodconsumption_frequency    0
Vegetable_consumption_frequency            0
Avg_no_of_meals                            0
Calorie_consumption_monitoring             0
Smoking_habits                             0
Water_consumption                          0
Family_history                             0
Physical_activity                          0
Mobile_screentime                          0
Food_consumed_between_meals                0
Transpotation                              0
obesity_level                              0
Bmi_index                                  0
dtype: int64

In [133]:
print(obesity_dataset_begin.duplicated().sum())

24

In [134]:
obesity_dataset_begin = obesity_dataset_begin.drop_duplicates()

In [135]:
obesity_dataset_begin.columns = obesity_dataset_begin.columns.str.strip()

In [136]:
print(obesity_dataset_begin.columns)

Index(['Age', 'Gender', 'Alcohol_consumption',
       'High_calories_foodconsumption_frequency',
       'Vegetable_consumption_frequency', 'Avg_no_of_meals',
       'Calorie_consumption_monitoring', 'Smoking_habits', 'Water_consumption',
       'Family_history', 'Physical_activity', 'Mobile_screentime',
       'Food_consumed_between_meals', 'Transpotation', 'obesity_level',
       'Bmi_index'],
      dtype='object')

In [137]:
obesity_dataset_begin.to_csv('obesity_final.csv', index=False)